<?php
namespace BTCec;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-05-15 at 09:22:52.
 */
class BTCSignTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var BTCSign
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BTCSign;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers BTCec\BTCSign::pubKeyFromSign
     * @todo   Implement testPubKeyFromSign().
     */
    public function testPubKeyFromSign()
    {
        $ec = $this->object;
        $ec->generateRandomPrivateKey();

        $priv_hex = $ec->getPrivateKey();

        $this->assertEquals(64,strlen($priv_hex));

        $pub_hex = $ec->getPubKey();

        $this->assertEquals(66,strlen($pub_hex));

        $message = "Test message for sign";

        $signature = $ec->signMessage($message, true);

        $derKey = $ec->pubKeyFromSign($signature, $message);

        $this->assertEquals($pub_hex, $derKey);
    }
}
